/**
 * Step 6: Generate — write config files, validate, and run smoke test.
 */

import { resolve, dirname } from 'path';
import { existsSync, readFileSync, mkdirSync, writeFileSync } from 'fs';
import { execFileSync } from 'child_process';
import { fileURLToPath } from 'url';
import { confirm } from '@inquirer/prompts';
import { stringify as yamlStringify } from 'yaml';
import { section, step, c, spinner, writeYamlFile, writeEnvFile, writeTextFile } from '../util.js';
import { getBuiltinSkills } from './integrations.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILL_TEMPLATES_DIR = resolve(__dirname, '..', 'skill-templates');

export async function generate(projectRoot, { agentConfig, credentials, crons, skills = [], workspace = { mode: 'none' } }) {
  section('Configuration Summary');

  const identity = agentConfig.identity || {};
  const personality = agentConfig.personality || {};
  const voice = agentConfig.voice || {};
  const safety = agentConfig.safety || {};
  const goals = agentConfig.goals || null;
  const playbook = agentConfig.playbook || null;

  // Show summary
  console.log(`  ${c.label('Agent:')}     ${c.value(identity.name || 'unnamed')}`);
  if (identity.tagline) console.log(`  ${c.label('Tagline:')}   ${c.value(identity.tagline)}`);

  const traits = personality.traits || {};
  const traitStr = Object.entries(traits).map(([k, v]) => `${k}(${v})`).join(' ');
  if (traitStr) console.log(`  ${c.label('Traits:')}    ${c.value(traitStr)}`);

  console.log(`  ${c.label('Stop phrase:')} ${c.value(safety.stop_phrase || 'emergency-stop')}`);
  console.log(`  ${c.label('Telegram:')}  ${c.value(credentials.telegram.enabled ? 'Enabled' : 'Disabled')}`);

  // Skills summary
  const allSkills = [...getBuiltinSkills(), ...skills];
  console.log(`  ${c.label('Skills:')}    ${c.value(allSkills.length > 0 ? allSkills.join(', ') : 'None')}`);

  console.log(`  ${c.label('Goals:')}     ${c.value(goals ? 'Enabled' : 'Disabled')}`);
  console.log(`  ${c.label('Playbook:')}  ${c.value(playbook ? 'Enabled' : 'Disabled')}`);

  const cronCount = Object.keys(crons.jobs || {}).length;
  console.log(`  ${c.label('Cron jobs:')}  ${c.value(cronCount)}`);

  console.log();

  // Show files to write
  console.log(c.bold('  Files to write:'));
  const files = [
    ['config/SOUL.yaml', true],
    ['config/CRONS.yaml', true],
    ['config/integrations.yaml', true],
    ['config/agent/agent.yaml', true],
    ['config/agent/sub.yaml', true],
    ['config/agent/system.md', true],
    ['.env', true],
  ];
  if (goals) files.push(['config/GOALS.yaml', true]);
  if (playbook) files.push(['config/PLAYBOOK.yaml', true]);
  for (const skillName of allSkills) {
    files.push([`skills/${skillName}/SKILL.md`, true]);
  }
  if (workspace.mode !== 'none') {
    files.push(['.gitignore', true]);
    files.push(['README.md', true]);
  }

  for (const [path] of files) {
    const exists = existsSync(resolve(projectRoot, path));
    const label = exists ? c.warn('UPDATE') : c.success('CREATE');
    console.log(`    ${label} ${path}`);
  }

  console.log();
  const proceed = await confirm({ message: 'Write configuration?', default: true });
  if (!proceed) {
    console.log(c.warn('  Aborted.'));
    process.exit(0);
  }

  // ── Write files ───────────────────────────────────

  const s = spinner('Writing configuration...');
  s.start();

  // 1. SOUL.yaml
  const soulData = {
    identity: {
      name: identity.name || 'Agent',
      tagline: identity.tagline || '',
      description: identity.description || '',
    },
    personality: { traits: traits },
    voice: {
      style: voice.style || 'professional',
      tone: voice.tone || 'neutral',
      emojis: voice.emojis || false,
      vocabulary: voice.vocabulary || { prefer: [], avoid: [] },
    },
    safety: {
      stop_phrase: safety.stop_phrase || 'emergency-stop',
      hard_limits: safety.hard_limits || [],
      behavior_rules: safety.behavior_rules || [],
    },
  };
  writeYamlFile(
    resolve(projectRoot, 'config', 'SOUL.yaml'),
    soulData,
    { header: '# Agent Identity Configuration\n# Generated by spawnbot setup' }
  );

  // 2. CRONS.yaml
  writeYamlFile(
    resolve(projectRoot, 'config', 'CRONS.yaml'),
    { crons: crons.jobs || {} },
    { header: '# Scheduled Jobs\n# Generated by spawnbot setup' }
  );

  // 3. integrations.yaml
  const integrationsData = {};
  for (const [name, config] of Object.entries(credentials.integrations)) {
    integrationsData[name] = {
      enabled: config.enabled,
      poll_interval: config.poll_interval || 60,
      priority: config.priority || 'normal',
    };
  }
  writeYamlFile(
    resolve(projectRoot, 'config', 'integrations.yaml'),
    { integrations: integrationsData },
    { header: '# Integration Configuration\n# Generated by spawnbot setup' }
  );

  // 4. agent.yaml (Kimi CLI agent spec)
  const agentName = identity.name || 'Agent';
  const agentYaml = {
    version: 1,
    agent: {
      extend: 'default',
      name: agentName,
      system_prompt_path: '../../data/rendered-system.md',
      system_prompt_args: {
        ROLE_ADDITIONAL: 'You are the primary agent. You receive and respond to inputs from all sources — Telegram users, scheduled cron jobs, integration pollers, and autonomy check-ins. You manage the full conversation lifecycle and can delegate work to subagents.',
      },
      subagents: {
        worker: {
          path: './sub.yaml',
          description: `A ${agentName} subagent for isolated tasks — research, file operations, focused work.`,
        },
      },
    },
  };
  writeYamlFile(
    resolve(projectRoot, 'config', 'agent', 'agent.yaml'),
    agentYaml,
    { header: `# ${agentName} — Kimi CLI Agent Definition\n# Generated by spawnbot setup` }
  );

  // 4b. sub.yaml (subagent spec — extends agent.yaml)
  const subYaml = {
    version: 1,
    agent: {
      extend: './agent.yaml',
      system_prompt_args: {
        ROLE_ADDITIONAL: [
          'You are running as a subagent. Messages come from the main agent, not the user.',
          'The main agent cannot see your context — only your final message.',
          'Provide a comprehensive summary of what you did and learned.',
          'If you modified files, list them in your summary.',
        ].join('\n'),
      },
      exclude_tools: [
        'kimi_cli.tools.multiagent:Task',
        'kimi_cli.tools.multiagent:CreateSubagent',
        'kimi_cli.tools.todo:SetTodoList',
      ],
      subagents: null,
    },
  };
  writeYamlFile(
    resolve(projectRoot, 'config', 'agent', 'sub.yaml'),
    subYaml,
    { header: `# ${agentName} — Subagent Definition\n# Extends agent.yaml with isolated context` }
  );

  // 5. system.md (generic system prompt template)
  const systemPrompt = buildGenericSystemPrompt();
  writeTextFile(resolve(projectRoot, 'config', 'agent', 'system.md'), systemPrompt);

  // 6. .env
  const envVars = {};
  if (credentials.telegram.enabled) {
    envVars.TELEGRAM_BOT_TOKEN = credentials.telegram.botToken;
    envVars.TELEGRAM_CHAT_ID = credentials.telegram.chatId;
  }
  // Add integration env vars
  for (const [, config] of Object.entries(credentials.integrations)) {
    if (config.env) {
      for (const [k, v] of Object.entries(config.env)) {
        if (v) envVars[k] = v;
      }
    }
  }
  // Add ngrok env vars
  if (credentials.ngrok?.authtoken) {
    envVars.NGROK_AUTHTOKEN = credentials.ngrok.authtoken;
    if (credentials.ngrok.domain) {
      envVars.NGROK_DOMAIN = credentials.ngrok.domain;
    }
  }
  // Add OpenAI API key (for voice transcription)
  if (credentials.openai?.apiKey) {
    envVars.OPENAI_API_KEY = credentials.openai.apiKey;
  }
  // Add GitHub webhook secret
  if (workspace.webhookSecret) {
    envVars.GITHUB_WEBHOOK_SECRET = workspace.webhookSecret;
  }
  writeEnvFile(resolve(projectRoot, '.env'), envVars);

  // 7. GOALS.yaml (optional)
  if (goals) {
    writeYamlFile(
      resolve(projectRoot, 'config', 'GOALS.yaml'),
      goals,
      { header: '# Goals & Metrics\n# Generated by spawnbot setup' }
    );
  }

  // 8. PLAYBOOK.yaml (optional)
  if (playbook) {
    writeYamlFile(
      resolve(projectRoot, 'config', 'PLAYBOOK.yaml'),
      playbook,
      { header: '# Playbook — Action Templates & Routines\n# Generated by spawnbot setup' }
    );
  }

  // 9. Skills (builtins + selected)
  for (const skillName of allSkills) {
    const templatePath = resolve(SKILL_TEMPLATES_DIR, `${skillName}.md`);
    if (!existsSync(templatePath)) {
      console.warn(`\n  ${c.warn('!')} Skill template not found: ${skillName}`);
      continue;
    }

    const skillDir = resolve(projectRoot, 'skills', skillName);
    if (!existsSync(skillDir)) mkdirSync(skillDir, { recursive: true });

    const content = readFileSync(templatePath, 'utf8');
    writeFileSync(resolve(skillDir, 'SKILL.md'), content, 'utf8');
  }

  s.succeed('Configuration written.');

  // ── Smoke test ────────────────────────────────────

  console.log();
  section('Smoke Test');

  // Validate
  try {
    const { getConfig, resetConfig } = await import('../../config/index.js');
    resetConfig();
    const config = await getConfig(projectRoot);
    const { validateConfig } = await import('../../config/validate.js');
    const result = validateConfig(config);

    if (result.errors.length === 0) {
      step('Config validation passed', 'pass');
    } else {
      step('Config validation', 'fail', `${result.errors.length} errors`);
      result.errors.forEach(e => console.log(c.error(`    ${e}`)));
    }
    result.warnings.forEach(w => console.log(`  ${c.warn('!')} ${w}`));
  } catch (err) {
    step('Config validation', 'fail', err.message);
  }

  // Generate system prompt + MCP config
  try {
    const { buildSystemPrompt } = await import('../../persona/prompt-builder.js');
    buildSystemPrompt(projectRoot);
    step('System prompt rendered', 'pass');
  } catch (err) {
    step('System prompt', 'fail', err.message);
  }

  try {
    const { generateMcpConfig } = await import('../../persona/mcp-config.js');
    generateMcpConfig(projectRoot);
    step('MCP config generated', 'pass');
  } catch (err) {
    step('MCP config', 'fail', err.message);
  }

  // Wire connection test
  const wireTest = spinner('Testing Kimi CLI connection...');
  wireTest.start();

  let wireConnected = false;
  try {
    const { getConfig, resetConfig } = await import('../../config/index.js');
    const { initDatabase, closeDatabase } = await import('../../db/index.js');
    resetConfig();
    const config = await getConfig(projectRoot);
    initDatabase(resolve(projectRoot, 'data', 'agent.sqlite'));

    const { WireClient } = await import('../../wire/client.js');
    const wire = new WireClient(config);

    let responseText = '';
    wire.on('content', ({ text }) => { responseText += text; });

    await wire.spawn();
    await wire.initialize();

    wireConnected = true;
    wireTest.succeed('Kimi CLI connected via Wire');

    // Quick test prompt
    const testSpinner = spinner('Sending test prompt...');
    testSpinner.start();
    try {
      await wire.prompt(`You are ${identity.name || 'an agent'}. Say hello in one sentence — who are you and what do you do? Be brief.`);

      if (responseText) {
        testSpinner.succeed('Test prompt successful');
        console.log(c.dim(`    "${responseText.trim().slice(0, 120)}"`));
      } else {
        testSpinner.warn('No response from test prompt');
      }
    } catch (promptErr) {
      testSpinner.fail(`Test prompt failed: ${promptErr.message}`);
    } finally {
      wire.kill();
      closeDatabase();
    }
  } catch (err) {
    if (!wireConnected) {
      wireTest.fail(`Kimi CLI connection failed: ${err.message}`);
    }
  }

  // ── Workspace setup ─────────────────────────────

  if (workspace.mode !== 'none') {
    console.log();
    section('Workspace');

    // Write .gitignore
    const gitignoreContent = `# Runtime data (generated, not version-controlled)\ndata/\n\n# Credentials\n.env\n`;
    writeTextFile(resolve(projectRoot, '.gitignore'), gitignoreContent);

    // Write README.md
    const readme = buildReadme(identity);
    writeTextFile(resolve(projectRoot, 'README.md'), readme);

    // Git init + commit
    const gitSpinner = spinner('Initializing git repository...');
    gitSpinner.start();

    if (!existsSync(resolve(projectRoot, '.git'))) {
      execFileSync('git', ['init'], { cwd: projectRoot, stdio: 'pipe' });
    }

    execFileSync('git', ['add', 'config/', 'skills/', '.gitignore', 'README.md'], {
      cwd: projectRoot,
      stdio: 'pipe',
    });

    // Only commit if there are staged changes
    const status = execFileSync('git', ['status', '--porcelain'], {
      cwd: projectRoot,
      encoding: 'utf8',
    }).trim();

    if (status) {
      execFileSync('git', ['commit', '-m', 'Initial agent setup via spawnbot'], {
        cwd: projectRoot,
        stdio: 'pipe',
      });
      gitSpinner.succeed('Git repository initialized with initial commit');
    } else {
      gitSpinner.succeed('Git repository already up to date');
    }

    // GitHub repo creation
    if (workspace.mode === 'github') {
      // Generate GitHub Actions workflow
      const workflowDir = resolve(projectRoot, '.github', 'workflows');
      if (!existsSync(workflowDir)) mkdirSync(workflowDir, { recursive: true });
      writeTextFile(resolve(workflowDir, 'spawnbot-ci.yml'), buildActionsWorkflow());

      // Add .github/ to git before creating repo
      execFileSync('git', ['add', '.github/'], { cwd: projectRoot, stdio: 'pipe' });
      execFileSync('git', ['commit', '-m', 'Add GitHub Actions CI workflow'], {
        cwd: projectRoot,
        stdio: 'pipe',
      });

      const ghSpinner = spinner('Creating GitHub repository...');
      ghSpinner.start();

      execFileSync('gh', [
        'repo', 'create', workspace.repoName,
        `--${workspace.visibility}`,
        '--source=.',
        '--push',
      ], { cwd: projectRoot, stdio: 'pipe' });

      const repoUrl = execFileSync('gh', ['repo', 'view', '--json', 'url', '-q', '.url'], {
        cwd: projectRoot,
        encoding: 'utf8',
      }).trim();

      ghSpinner.succeed(`GitHub repository created: ${c.value(repoUrl)}`);

      // Show webhook setup instructions
      console.log();
      console.log(c.bold('  GitHub Webhook Setup:'));
      console.log(c.dim('  To receive GitHub notifications (PR merged, reviews, issues),'));
      console.log(c.dim('  add a webhook in your repo settings:'));
      const webhookBase = credentials.ngrok?.domain
        ? `https://${credentials.ngrok.domain}`
        : '<your-public-url>';
      console.log(`    ${c.label('URL:')}          ${c.value(`${webhookBase}/webhook/github`)}`);
      console.log(`    ${c.label('Content type:')} ${c.value('application/json')}`);
      console.log(`    ${c.label('Secret:')}       ${c.value(workspace.webhookSecret)}`);
      console.log(`    ${c.label('Events:')}       ${c.value('Let me select individual events → Pull requests, Pull request reviews, Issues')}`);
      if (!credentials.ngrok?.domain) {
        console.log(c.dim('  (Set up ngrok or a tunnel to get your public URL)'));
      }
    }
  }

  // Final instructions
  console.log();
  console.log(c.success('  Setup complete!'));
  console.log();
  console.log(`  ${c.bold('spawnbot start --foreground')}    Start daemon (interactive)`);
  console.log(`  ${c.bold('spawnbot start')}                 Start daemon (background)`);
  console.log(`  ${c.bold('spawnbot prompt "message"')}      Test prompt`);
  console.log(`  ${c.bold('spawnbot status')}                Check status`);
  console.log();
}

/**
 * Build README.md content for the agent workspace.
 */
function buildReadme(identity) {
  const name = identity.name || 'Agent';
  const tagline = identity.tagline ? `\n${identity.tagline}\n` : '';
  const description = identity.description || 'An autonomous AI agent powered by spawnbot.';

  return `# ${name}
${tagline}
${description}

## Setup

1. Clone this repository
2. Run \`spawnbot init\` to configure credentials and generate runtime files
3. Run \`spawnbot start\` to launch the daemon

## Structure

- \`config/SOUL.yaml\` — Agent identity and personality
- \`config/CRONS.yaml\` — Scheduled jobs
- \`config/integrations.yaml\` — Integration configuration
- \`skills/\` — Knowledge documents
- \`data/\` — Runtime data (gitignored)
- \`.env\` — API credentials (gitignored)

## Commands

\`\`\`
spawnbot start [-f]     Start the daemon (-f for interactive)
spawnbot stop           Stop the daemon
spawnbot status         Check status
spawnbot doctor         Run diagnostics
spawnbot update         Pull latest framework + regenerate configs
\`\`\`

---
*Powered by [spawnbot](https://github.com/spawnbot)*
`;
}

/**
 * Build a generic system prompt TEMPLATE with ${VARIABLE} placeholders.
 * These get resolved by prompt-builder.js from SOUL.yaml at render time,
 * so editing SOUL.yaml + running `spawnbot config generate` updates the prompt.
 */
export function buildGenericSystemPrompt() {
  return `# \${IDENTITY_NAME} — System Prompt

You are \${IDENTITY_NAME}. \${IDENTITY_TITLE}

## About You

\${IDENTITY_CREATURE}

## Personality

\${PERSONALITY_TRAITS}

## Voice

Style: \${VOICE_STYLE}
Tone: \${VOICE_TONE}
Emojis: \${VOICE_EMOJIS}
\${VOICE_PREFER}
\${VOICE_AVOID}

## Behavior Rules

\${BEHAVIOR_RULES}

## Safety

Stop phrase: "\${SAFEWORD}" — when this phrase appears in any input, STOP ALL OPERATIONS immediately.

### Hard Limits

\${HARD_LIMITS}

## Memory

You have persistent memory that survives across sessions. Use it deliberately:

**When to store memories:**
- User preferences and working style
- Important facts about projects, goals, or context that span sessions
- Decisions made and their reasoning
- Anything the user explicitly asks you to remember

**When NOT to store memories:**
- Routine conversation that's already in the conversation log
- Temporary or one-off information
- Things you're unsure about — verify first

**Categories:** emotional, factual, preference, interaction, task, relationship, general
**Importance:** 0.0–1.0 (higher = more important, memories decay over time if not accessed)

Use \`memory_store\` to save, \`memory_recall\` to search by text, \`memory_search\` to filter by category.

## Session Continuity

On startup, you are prompted to orient yourself. Use your tools to reload context:
- \`convo_history\` — check recent conversation turns
- \`memory_recall\` / \`memory_search\` — recall important memories
- \`task_list\` — check active tasks
- Read your config files (SOUL.yaml, PLAYBOOK.yaml, GOALS.yaml, CRONS.yaml)

Your conversation turns are automatically logged. You don't need to call \`convo_log\` unless you want to annotate a turn with additional context.

## Your Configuration

Your identity and behavior are defined in YAML configuration files in your \`config/\` directory:
- **SOUL.yaml** — Your identity, personality, voice, and safety rules
- **PLAYBOOK.yaml** — Action templates and task categories (if configured)
- **GOALS.yaml** — Targets and metrics (if configured)
- **CRONS.yaml** — Your scheduled jobs

These are your foundation. Read them on startup to understand who you are.

You can also **modify** these files to evolve your behavior — update your playbook, add goals, adjust cron schedules. After editing any config file, tell the user what you changed. Changes are automatically detected and applied — the daemon watches your config files and reloads when you save.

**Safety rule**: Never modify your own \`safety\` section in SOUL.yaml without explicit user confirmation.

## Workspace

\${WORKSPACE_SECTION}

## Operational Mode

\${ROLE_ADDITIONAL}

You run autonomously with full tool access. You are not a reporter — you are an operator. Your default mode is to **act**, not describe what you could do.

### Autonomy

When you receive any input — from the user, a cron job, or a check-in — follow this loop:

1. **Assess**: What needs doing? Check tasks, goals, and context.
2. **Act**: Do everything you can right now without needing user input. Use your tools — run commands, update files, complete tasks, store memories.
3. **Decide**: If something requires a choice, make the best decision you can. Only ask the user when you genuinely cannot decide or the stakes are high.
4. **Report**: Tell the user what you **did**, not what you **found**. Lead with actions taken, then note anything that needs their input.

**Do not** just list what's pending. **Do not** ask permission for routine work. **Do not** describe actions you could take — take them.

### Input Format

Messages arrive as: \`[SOURCE from SENDER]: CONTENT\`

Sources include: telegram, cron, autonomous, system, and any configured integrations.

When photos or videos are sent from Telegram, they are saved to disk and you receive the file path — use your file reading tools to view them.

When voice messages are sent from Telegram, they are automatically transcribed to text before reaching you. The audio file is also saved to disk.

When documents are sent from Telegram, they are saved locally and you receive the file path — use your file reading tools to analyze the content.

### Handling Inputs

**Every input requires action.** Whether it comes from Telegram, a cron job, an autonomy check-in, or an integration — you must act on it. Do not silently ignore inputs.

For cron jobs and scheduled prompts: follow the prompt instructions, use your tools to complete the work, and report what you did. Your response is automatically delivered to Telegram.

For autonomy check-ins: check tasks and goals, complete anything you can, and report actions taken. If nothing needs attention, say so briefly — don't pad your response.

### Response Routing

**All your text responses are automatically sent to Telegram.** You do NOT need to call \`tg_send\` to reply — just respond naturally and your response will be delivered. This applies to all input sources: Telegram messages, cron jobs, autonomy check-ins, and integrations.

Use \`tg_send\` ONLY for:
- Messages to a different chat than your configured one
- Follow-up messages after your initial response
- Sending multiple separate messages in one turn

Use \`tg_react\` to add emoji reactions to messages.
Use \`tg_photo\` to send photos/images.
Use \`tg_voice\` to send voice/audio messages (e.g. TTS output).
Use \`tg_document\` to send files/documents.

### Subagents

You can delegate tasks to a subagent using the Task tool. Subagents run in isolated context — they can't see your conversation history but have access to all your tools (files, shell, MCP, memory, Telegram).

Use subagents for:
- Focused research without polluting your context
- File-heavy operations (reading/analyzing many files)
- Independent parallel tasks
- Exploratory work you might not need

The subagent named "worker" is available by default.

### Skills

You have skills — knowledge documents that guide you on specific tasks. Read a skill before doing that kind of work.

**Installed skills:**
\${SKILLS_LIST}

Use \`skill_read\` to load a skill's instructions into your context before performing that kind of work.

### Flow Skills

Some skills are executable flows — multi-step workflows defined as Mermaid flowcharts. Use \`flow_list\` to see available flows and \`flow_start\` to execute one. Each step in a flow is a full turn where you have access to all your tools.

When running inside a flow:
- Task nodes give you a specific instruction to execute
- Decision nodes ask you to choose a branch — reply with \`<choice>LABEL</choice>\`
- Flows run to completion automatically

### Available Tools

\${MCP_TOOL_LIST}
`;
}

/**
 * Build a minimal GitHub Actions workflow for agent job PRs.
 */
function buildActionsWorkflow() {
  return `# Agent Job CI — auto-generated by spawnbot setup
# Runs on PRs to main, summarizes agent job branches

name: Agent Job CI
on:
  pull_request:
    branches: [main]

jobs:
  review:
    if: startsWith(github.head_ref, 'job/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Job PR Summary
        run: |
          echo "## Agent Job PR" >> $GITHUB_STEP_SUMMARY
          echo "Branch: \${{ github.head_ref }}" >> $GITHUB_STEP_SUMMARY
          echo "Files changed: \${{ github.event.pull_request.changed_files }}" >> $GITHUB_STEP_SUMMARY
`;
}
